export const FETCH_USERS = "FETCH_USERS";
export const ADD_USER = "ADD_USER";
export const FETCH_USER = "FETCH_USER";
export const ADD_DATE = "ADD_DATE";
export const FETCH_FOODS = "FETCH_FOODS";
export const FETCH_ACTIVITIES = "FETCH_ACTIVITIES";
export const ADD_USER_CALORIE_IN_BY_ID_AND_DATE =
  "ADD_USER_CALORIE_IN_BY_ID_AND_DATE";
export const ADD_USER_CALORIE_OUT_BY_ID_AND_DATE =
  "ADD_USER_CALORIE_OUT_BY_ID_AND_DATE";
