export const SHOW_ADD_USER_MODEL = "SHOW_ADD_USER_MODEL";
export const HIDE_ADD_USER_MODEL = "HIDE_ADD_USER_MODEL";
export const SHOW_ADD_USER_CALORIE_IN_MODEL = "SHOW_ADD_USER_CALORIE_IN_MODEL";
export const HIDE_ADD_USER_CALORIE_IN_MODEL = "HIDE_ADD_USER_CALORIE_IN_MODEL";
export const SHOW_ADD_USER_CALORIE_OUT_MODEL =
  "SHOW_ADD_USER_CALORIE_OUT_MODEL";
export const HIDE_ADD_USER_CALORIE_OUT_MODEL =
  "HIDE_ADD_USER_CALORIE_OUT_MODEL";
export const SHOW_SNACKBAR = "SHOW_SNACKBAR";
export const HIDE_SNACKBAR = "HIDE_SNACKBAR";
